export const useTheme = () => ({
    bg: '#f2f6f6',
    card: '#ffffff',
    text: '#111827',
    subtext: '#6b7280',
    border: '#f3f4f6',
    inputBg: '#ffffff',
    inputText: '#111827',
    inputPlaceholder: '#9ca3af',
    chipBg: '#f0fafa',
    chipBorder: '#cceaea',
    chipText: '#02757A',
    sectionLabel: '#374151',
    headerBgRestaurant: '#e6f4f4',
    headerBgTiffin: '#f5efe8',
    headerBgEvents: '#efe9f6',
    headerBgSettings: '#f0f4ff',
    headerCircleRestaurant: '#d6efef',
    headerCircleTiffin: '#efe6db',
    headerCircleEvents: '#e3daf0',
    headerCircleSettings: '#e1e9ff',
});
